
CREATE TABLE users(id BIGINT PRIMARY KEY AUTO_INCREMENT,username VARCHAR(100),password VARCHAR(255),role VARCHAR(20));
CREATE TABLE doctor(id BIGINT PRIMARY KEY AUTO_INCREMENT,name VARCHAR(100),specialization VARCHAR(100));
CREATE TABLE patient(id BIGINT PRIMARY KEY AUTO_INCREMENT,name VARCHAR(100),email VARCHAR(100));
CREATE TABLE appointment(id BIGINT PRIMARY KEY AUTO_INCREMENT,doctor_id BIGINT,patient_id BIGINT,appointment_time DATETIME,status VARCHAR(20));
